movieapp/urls.py
from django.urls import path
from . import views # importing views module from current folder

app_name = "movieapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>', views.details, name='details'),
    path('add/', views.add, name='add'),
    path('edit/<int:movie_id>', views.edit, name='edit'),
    path('delete/<int:movie_id>', views.delete, name='delete')
]

movies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]

from django.conf.urls.static import static
from movies import settings

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to='pics')
    desc = models.TextField()
    year = models.IntegerField()

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'image', 'desc', 'year']

movieapp/views.py
from django.shortcuts import render
from . models import Movie
from . forms import MovieForm
from django.contrib import messages
from django.shortcuts import redirect

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    return render(request, 'index.html', {'movies': movies})

def details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'details.html', {'movie': movie})

def add(request):
    if request.method == 'POST':
        name = request.POST['name']
        image = request.FILES['image']
        year = request.POST['year']
        desc = request.POST['desc']

        movie = Movie(name=name, image=image, year=year, desc=desc)
        movie.save()

        messages.info(request, name + " has been added")

        return redirect('/add')

    return render(request, 'add.html')

def edit(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request, 'edit.html', {'form': form, 'movie': movie})

def delete(request, movie_id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=movie_id)
        movie.delete()
        return redirect('/')

    return render(request, 'delete.html')

movieapp/templates/add.html
{% extends 'base.html' %}
{% block body %}
    <div class="container mt-3">
        <h2 class="mb-3">Add Movie</h2>

        <form class="mb-3" method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row mb-3">
                <label for="name" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="name" id="name">
                </div>
            </div>
            <div class="row mb-3">
                <label for="year" class="col-sm-2 col-form-label">Year</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="year" id="year">
                </div>
            </div>
            <div class="row mb-3">
                <label for="image" class="col-sm-2 col-form-label">Poster</label>
                <div class="col-sm-10">
                    <input type="file" class="form-control" name="image" id="image">
                </div>
            </div>
            <div class="row mb-3">
                <label for="desc" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-10">
                    <textarea class="form-control" name="desc" id="desc" rows="4"></textarea>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="container">
        <div>
            {% for msg in messages %}
                <h4>{{ msg }}</h4>
            {% endfor %}
        </div>
    </div>
{% endblock %}

movieapp/templates/delete.html
{% extends 'base.html' %}
{% block body %}
    <div class="container mt-3">
        <h2 class="mb-3">Delete Movie</h2>

        <form class="mb-3" method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            Are you sure you want to delete this movie
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-danger">Yes</button>
                <a class="btn btn-primary" href="/" role="button">No</a>
            </div>
        </form>
    </div>
{% endblock %}

movieapp/templates/details.html
{% extends 'base.html' %}
{% block body %}
    <div class="container mt-3">
        <h2 class="">{{ movie.name }}</h2>
        <h4 class="mb-3">{{ movie.year }}</h4>
        <div class="row">
            <div class="col-3">
                <img src="{{ movie.image.url }}" style="width: 100%;" alt="movie_poster">
            </div>
            <div class="col-8">
                <p>{{ movie.desc }}</p>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a class="btn btn-primary" href="{% url 'movieapp:edit' movie.id %}" title="edit {{ movie.name }}" role="button">
                        <i class="fa-solid fa-pen-to-square"></i> Edit
                    </a>
                    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}" title="delete {{ movie.name }}" role="button">
                        <i class="fa-solid fa-trash-can"></i> Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

movieapp/templates/edit.html
{% extends 'base.html' %}
{% block body %}
    <div class="container mt-3">
        <h2 class="mb-3">Edit Movie</h2>

        <form class="mb-3" method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

movieapp/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h1 class="mt-3 mb-3">Movies</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for i in movies %}
        <div class="col">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ i.image.url }}" class="img-fluid rounded-start" style="height: 100%" alt="{{ i.name }}">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <a href="{% url 'movieapp:details' i.id %}">
                                <h5 class="card-title movie_name" title="{{ i.name }}">{{ i.name }}</h5>
                            </a>
                            <p class="card-text"><small class="text-muted">{{ i.year }}</small></p>
                            <p class="card-text">{{ i.desc }}</p>
                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                <a class="btn btn-primary" href="{% url 'movieapp:edit' i.id %}" title="edit {{ i.name }}" role="button">
                                    <i class="fa-solid fa-pen-to-square"></i> Edit
                                </a>
                                <a class="btn btn-danger" href="{% url 'movieapp:delete' i.id %}" title="delete {{ i.name }}" role="button">
                                    <i class="fa-solid fa-trash-can"></i> Delete
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <title>Movie App</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

        <!-- font awsome -->
        <script src="https://kit.fontawesome.com/2b2b328c2a.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Movie App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link active" aria-current="page" href="#">Home</a>-->
<!--                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/add">Add</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin">Admin</a>
                        </li>
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link" href="#">Pricing</a>-->
<!--                        </li>-->
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link disabled">Disabled</a>-->
<!--                        </li>-->
                    </ul>
                </div>
            </div>
        </nav>

        {% block body %}
        {% endblock %}
    </body>
</html>